### ISSUE TITLE
Add mentioned users to watcher list

### ISSUE THREAD

**Issue by morph027** [arkhitech/redmine_mentions#15]
Just using your plugin for some time now and we love it. However, some of us like the idea of being noticed when something happens in an issue they were mentioned. https://github.com/stpl/redmine_mention_plugin has some code for this (in lib/mention/issue_patch.rb). Any chance you like this idea too? ;)

**Comment by hryamzik** [comment]
This topic is a bit old but anyway, @morph027, why don't you just use plugin you've mentioned?

**Comment by morph027** [comment]
Hm, last time i've tried it does not work with latest Redmine... ;)

**Comment by hryamzik** [comment]
There's a fix in PRs now.

**Comment by giRobert** [comment]
I guess this was not introduced?
