### ISSUE TITLE
Does not complete names when editing a comment

### ISSUE THREAD

**Issue by Androc** [arkhitech/redmine_mentions#24]
If you edit a comment in issue, the plugin does not complete names.

**Comment by jasonzzz** [comment]
The plugin will not send a email unless you open a new comment/issue.

**Comment by Androc** [comment]
Is it the intended behavior? It means that if you forgot to mention someone, you can't edit your comment to mention him, you are forced to create a new comment just to mention him.
It leads to some "useless" comments, no?

**Comment by jasonzzz** [comment]
I think it's not.

When opening a new comment, you will call `Mailer.message_posted` in app/models/mailer.rb. There's no method like `Mailer.message_edited`.
Thus even if you edit a comment, Redmine will not send a mail/mention.

**Comment by Androc** [comment]
Oh OK. I understand. Thanks for your answer.
