### ISSUE TITLE
no auto-complete

### ISSUE THREAD

**Issue by fannheyward** [arkhitech/redmine_mentions#31]
I have installed plugin in `plugins`, and restart with `service apache2 restart`.

The plugin can be found in `admin/plugins`, but there is no auto-complete when I mentioned someone in Notes. 

Is there something wrong of my usage?

Thanks.

**Comment by jamesepatrick** [comment]
I don't believe this has support for autocomplete.

Additionally you may still need to do a rake to enable this.
See https://www.redmine.org/projects/redmine/wiki/Plugins
