### ISSUE TITLE
Make mentions non-case sensitive

### ISSUE THREAD

**Issue by amenk** [arkhitech/redmine_mentions#43]
The mentions seem to be case sensitive (if the autocomplete is not used)

**Comment by RazZziel** [comment]
Even if the autocomplete is used, usernames with caps and symbols confuse the plugin:

* Normal behavior: User login `@user`, I write `@user`, the plugin replaces `@user` with User's name, User receives his email
* Abnormal behavior:
  * User login `@User`, I write `@User`, the plugin **doesn't** replace `@user` with User's name, User **does** receive his email
  * User login `@User`, I write `@user`, the plugin **does** replace `@user` with User's name
  * User login `@user.2`, I write `@user.2`, the plugin **doesn't** replace `@user` with User's name
  * User login `@user_2`, I write `@user_2`, the plugin **doesn't** replace `@user` with User's name

**Comment by RazZziel** [comment]
Turns out it's a Redmine bug, fixed it on https://github.com/imasdetres/redmine/commit/fc03480fef84dddcd1807666e0cfc7c7831be1ae

**Comment by amenk** [comment]
@RazZziel so were you able to send mentions to users which logged in using "CAPS" ? We create the user names from LDAP, so does it mean the redmine bug fixed the users beeing created in CAPS ? does it mean we should lower-case als the existing users via a SQL query?

**Comment by RazZziel** [comment]
After that patch, mentions are working fine for me on user logins with mixed upper and lower case letters; if you can apply it I don't think you need to fix user logins with SQL.
