### ISSUE TITLE
Now working in redmine version 5

### ISSUE THREAD

**Issue by hynekpetrla** [arkhitech/redmine_mentions#78]
Hello, we have issue with run this plugin on redmine 5 version. Any advice how to renable this plugin? 
Is a compatibility update planned?

Thanks

**Comment by mensfeld** [comment]
The most recent master works well with Redmine 5 for me.

**Comment by elveadk** [comment]
Hello,
We have issue too with run this plugin on redmine 5 version. How run this plugin ?
Thanks for your help.

**Comment by hynekpetrla** [comment]
We found, that redmine 5 implemented mention by default. Soo this plugin is not needed more.
